project_id = "oejrddkmhbcbhyetzeny"

[functions.analyze-image]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.generate-entity-sketch]
verify_jwt = false

[functions.daily-tarot]
verify_jwt = false

[functions.numerology-reading]
verify_jwt = false

[functions.psychic-chat]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.get-user-data]
verify_jwt = false
